name: nuget publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
    steps:
      uses: actions/checkout@main
      - name: Listing
        run: ls
      - name: Restore
        run: dotnet restore ReCron.sln
      - name: Build
        run: dotnet build ReCron.sln

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
    steps:
      - name: Test
        run: dotnet test

  nuget-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
    steps:
      - name: Packing
        run: dotnet pack src/ReCron/ReCron.csproj -c Release
      - name: Nuget Push
        run: dotnet nuget push src\ReCron\bin\Release\ReCron.0.1.2.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
